#!/usr/bin/env ruby

require 'optparse'
require 'swagger/diff'

options = {}
OptionParser.new do |opts|
  opts.banner = 'Usage: swagger-diff [options] <old> <new>'

  opts.on('-c', '--changes',
          'Generate a list of changes between <new>',
          'and <old>') do |c|
    options[:changes] = c
  end

  opts.on('-i', '--incompatibilities',
          'Checks <new> for backwards-compatibility',
          'with <old>. If <new> is incompatible, a',
          'list of incompatibilities will be printed.') do |i|
    options[:incompatibilities] = i
  end

  opts.on('--csv',
    'Outputs to CSV.',
    'If not specificed outputs as YAML') do |csv|
    options[:csv] = csv
  end

  opts.on_tail('-h', '--help', 'This message') do
    puts opts
    exit
  end

  opts.on_tail('-v', '--version', 'Display the version') do
    puts Swagger::Diff::VERSION
    exit
  end

  options[:help] = opts
end.parse!

if ARGV.length == 2
  diff = Swagger::Diff::Diff.new(ARGV[0], ARGV[1])
  
  if options[:changes]
    if options[:csv]
      puts diff.changes_message("csv")    
    else
      puts diff.changes_message("yaml")
    end
  else
    unless diff.compatible?
      if options[:csv]
        puts diff.incompatibilities_message("csv")
      else
        puts diff.incompatibilities_message("yaml")
      end
      exit 1
    end
  end
else
  puts options[:help]
end
